### ISSUE TITLE
Ubuntu 20.04 LTS - Zesarux Only Works in Command Line

### ISSUE THREAD

**Issue by MDB00** [VR51/ZEsarUX-Installer#2]
I've installed Zesarux under Ubuntu 20.04 LTS. Typing "zesarux" at the command line causes it to run and, having selected the Jupiter Ace (which is what I'm interested in), I can execute Forth commands successfully at the command line. However, I'd like to see a "real" Jupiter Ace display and keyboard for which, I assume, I need to run the GUI version of Zesarux. Looking in the Applications Overview, I note that Zesarux is shown, but instead of a specific Zesarux icon, it has an icon very similar to Settings, so I assume that it hadn't installed correctly. This assumption seems to be confirmed by attempting to run Zesarux from this icon, since nothing happens.

FYI, I've tried the installation twice with the same effect. I have also rebooted after installation, but that made no difference. I perhaps also ought to point out that, despite the bash script suggesting that the installation might take a long time, it completed in one or two minutes.

Any assistance you can offer would be very much appreciated.

**Comment by VR51** [comment]
I've just replied to your other support request re the icon file. The developer of Zesarux has moved the file's location so I've updated the script to make it grab the correct icon. I wrote this script to simplify the installation and update of Zesarux; I'm not the author of Zesarux.

About the Jupiter Ace display. Zesarux has a number of GUI options. You need to use your mouse to click the screen to bring up machine options. I've not used Jupiter Ace. There is documentation for it here (you will need Download the PDF there) https://github.com/chernandezba/zesarux-extras/blob/master/extras/docs/jupiter_ace/JA-Manual-Second-Edition.pdf

**Comment by MDB00** [comment]
Thanks again for your help Lee. I've tried installing again but zesarux still doesn't show with its proper icon. However, that's not really an big problem, the main issue still is that attempting to run zesarux from the default icon simply doesn't work, i.e. nothing happens at all. And although I can run zesarux from the command line, unless there is some convoluted sequence of menu settings needed, that only gives me a textual emulation, not anything that looks at all like the Jupiter Ace (i.e. I'm not seeing anything outside of the terminal window). I note that, when I run zesarux, it says that it's a snapshot version and it might not work correctly, and while I wondered if that was the reason for the problem, I find it hard to believe that something would be released that doesn't work in such a fundamental way. In view of what you said about not being the author of zesarux, perhaps I should take this up with the author instead - do you know if he's responsive to queries like this?

Also, thanks for the link to the Jupiter Ace manual, but unless it has a very obscure filename, I'm coming to the conclusion that there is no user manual for zesarux. Is that correct?

**Comment by VR51** [comment]
Do you see the GUI when you choose other emulated systems? There are different windowing systems within Zesarux. My config is pasted below here, it might help you. Maybe there is an issue within Zesarux that affects only new installs. I didn't get to try a fresh install yesterday but I was able to rebuild Zesarux and run it on my own system, Kubuntu 20:10, which was 20.04 until recently and it worked then too.

When I load the Jupiter Ace emulator I see a black screen with a command prompt at the bottom of the screen placed similarly to where it is for a 48k Spectrum. Not being familiar with the Jupiter Ace I have no idea what is meant to display for the Jupiter Ace. What you should be able to access, though, is the Zesarux GUI by left clicking over the open window. You can press F1 to open help (I think). Is Zesarux opening at your full-screen size or is it opening windowed?

Cesar has been responsive to my queries in the past. I can't recall how I got a'hold of him last time but as a general tip you can create a GitHub repo, call it e.g. coms, then @ address GitHub users in an issue under that dummy repository; I did similar here when I needed to message someone https://github.com/VR51/messaging.

## My Zesarux Config File

This file is from ~/.zesaruxrc e.g. /home/your-username/

I have only just seen that we can start with `zesarux --experthelp` to see more options.

```
;ZEsarUX configuration file
;
;Lines beginning with ; or # are ignored
;You can specify here the same options passed on command line, for example:
;--verbose 2
;Options can be written in quotation marks, for example:
;--joystickemulated "OPQA Space"
;Options can be written on the same line or different lines, like:
;--verbose 2 --machine 128k
;Or:
;--verbose 2
;--machine 128k
;Or even like this:
;--verbose
;2
;--machine
;128k

;Run zesarux with --help or --experthelp to see all the options

--saveconf-on-exit 
--zoom 3 
--menucharwidth 6 
--reduce-075-offset-x 0 
--reduce-075-offset-y 0 
--watermark-position 3 
--zxdesktop-width 256 
--zxdesktop-fill-type 1 
--zxdesktop-fill-primary-color 0 
--zxdesktop-fill-secondary-color 13 
--tbblue-max-turbo-rom 1 
--ao pulse 
--vo xwindows 
--disable-silencedetector 
--pcspeaker-wait-time 8 
--kempstonmouse-sens 1 
--no-spectrum-reduced-core 
--machine ACE 
--allpixeltotext-scale 10 
--vsync-minimum-length 518 
--smartloadpath "" 
--addlastfile "" 
--keymap 0 
--arttextthresold 4 
--textfps 10 
--tool-sox-path "/usr/bin/sox" 
--tool-gunzip-path "/bin/gunzip" 
--tool-tar-path "/bin/tar" 
--tool-unrar-path "/usr/bin/unrar" 
--diviface-ram-size 128 
--showfiredbreakpoint 0 
--menu-mix-method "Over" 
--menu-transparency-perc 10 
--realvideo 
--enablegigascreen 
--totalaychips 2 
--ay-stereo-channel A 0 
--ay-stereo-channel B 1 
--ay-stereo-channel C 2 
--enableaudiodac 
--audiodactype "Specdrum" 
--midi-client 0 
--midi-port 0 
--midi-raw-device hw:0,0 
--no-first-aid filesel_uppercase_keys 
--no-first-aid filesel_enter_key 
--no-first-aid smartload 
--no-first-aid initial_menu 
--no-first-aid no_ssl_wos 
--no-first-aid realjoystick_detected 
--no-first-aid sg1000_boot 
--no-first-aid startup_aid 
--no-first-aid multiplattform 
--no-first-aid accessibility 
--gui-style "ZEsarUX" 
--zeng-remote-port 10000 
--zeng-snapshot-interval 2 
--total-minutes-use 26 
--stats-send-already-asked 
--stats-speccy-queries 0 
--stats-zx81-queries 0 
--stats-last-avail-version 9.1 
--last-version "1609613249" 
--windowgeometry filesel 5 4 30 23 
--windowgeometry aypiano 15 0 17 13 
--windowgeometry ayregisters 1 5 30 14 
--windowgeometry aysheet 0 0 32 24 
--windowgeometry ayplayer 6 9 32 20 
--windowgeometry wavepiano 13 5 19 8 
--windowgeometry waveform 1 1 30 19 
--joystickemulated "Cursor&Shift" 
--remoteprotocol-port 10000 
--realjoystickpath /dev/input/js0 
--realjoystick-calibrate 16383 
--text-keyboard-add "~~north" 
--text-keyboard-add "~~west" 
--text-keyboard-add "~~east" 
--text-keyboard-add "~~south" 
--text-keyboard-add "loo~~k" 
--text-keyboard-add "e~~xamine" 
--text-keyboard-add "~~help" 
--text-keyboard-add "~~talk" 
--text-keyboard-add "ex~~it" 
--text-keyboard-length 50 

```

**Comment by MDB00** [comment]
Hello Lee, PC turned off right now, and I'm back at work in the morning, hence this quick email response.

As a brief answer to your question about whether I see a window or a full screen display, I don't see either. If I try to execute zesarux from the icon, nothing happens at all. If I type zesarux at a command prompt, it does start but only as a textual dialogue - no window opens outside the terminal Window. So I can select menu items and when I choose the Jupiter Ace I can execute FORTH instructions but that all takes place in the terminal Window.

Regards,
Mike

[Edited by VR51 to remove duplicate message part]

**Comment by VR51** [comment]
I think I see what is happening now. The GUI is not launching (sorry for stating the obvious, it's only stated for people who skim-read to this point in our conversation).

When I launch Jupiter Ace I see what is shown in the below screenshot. I suspect that if you use the config file I pasted above you might get to see the GUI then you should be able to adjust to taste.

I've edited the installer script to make it install all available Linux launcher icons for ZEsarUX. Later on, possibly this week, if my config file resolves the issue for you I will add an option to download a config file that enables the GUI.

Thanks for replying, Mike. I will look in on this again tomorrow.

![image](https://user-images.githubusercontent.com/5859901/103486287-b17c3b80-4df4-11eb-8c61-31d555aef726.png)

**Comment by MDB00** [comment]
Thanks again for you help Lee. I've created a config file with the contents you provided, but I'm not sure what I should call it and, unless it's well hidden, it doesn't appear that I'd be replacing an existing config file (in which case I'd have known the filename). I tried calling it zesarux.conf and putting it in /home/my-username/ and I also tried calling it zesarux.config. There was no file of either name in that directory, indeed there was nothing zesarux-related in /home/my-username/ except for the /src folder, inside which is the /zesarux folder. I did try putting the file at /home/my-username/src/zesarux with both filenames. In all these cases, zesarux still stubbornly refused to work by clicking on its icon and, again, nothing appeared outside the terminal window (i.e. no GUI) if I ran zesarux from a command line.

**Comment by VR51** [comment]
It's a dot file so the leading full-stop is important in the file name. The file goes under, and is called, `/home/your-username/.zesaruxrc` (notice the dot in front of **.zesaruxrc**). You might need to adjust your file browser's display settings to enable the visibility of hidden files otherwise dot files won't be browsable.

**Comment by MDB00** [comment]
Thanks, I understand, and I've deleted the old config file and generated a new one with your suggested contents. Still nothing happens if I click on the icon but the behaviour has changed if I execute zesarux from the command line. Now it displays a few lines of introductory text and then exits. I assume, at this point, the GUI should start, but it doesn't. No longer does it allow me to select options in the terminal window and execute an emulation, albeit in a limited "text only in the terminal widow" sort of way. It did occur to me that, if the GUI has always worked for you, it's possible that you've never seen what I see in the terminal window. So, here's what I see in the terminal window by typing zesarux at the command prompt with just the default config file (or, in the case of this particular time, with no config file):

mike@Mike-PC:~$ zesarux
ZEsarUX - ZX Second-Emulator And Released for UniX
https://github.com/chernandezba/zesarux

Copyright (C) 2013 Cesar Hernandez Bano

ZEsarUX is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.

Please read the other licenses used in ZEsarUX, from the menu Help->Licenses or just open files from folder licenses/


ZEsarUX v.9.2-SN - xxxxxx edition. 14 December 2020

Configuration file /home/mike/.zesaruxrc not found
Creating a new one
Build number: 1609674990
WARNING. This is a Snapshot version and not a stable one
Some features may not work, random crashes could happen, abnormal CPU use, or lots of debug messages on console

Kernel panic - not syncing: VFS: Unable to mount root fs on unknown-block(179,2) ... Just kidding ;)

Press { to manual redraw screen. Press } to automatic redraw screen
Write 'menu' to open the menu
Write 'esc' to simulate ESC key on some menu dialogs
Error:    Error asking permissions on speaker port
-ERROR-

Error asking permissions on speaker port

ZEsarUX v.9.2-SN
------------------------

 1)Smart load
 2)Snapshot
 3)Machine
 4)Audio
 5)Display
 6)Storage
 7)Debug
 8)Network

10)Settings
11)Help...
12)ESC Back
13)Exit emulator

Option number? (prepend the option with h for help, t for tooltip). Write esc to go back.

**Comment by VR51** [comment]
You are right. I've never seen it load that way.

Enter Settings (option 10) and you should then be able to cycle through the display and GUI settings for Zesarux.

Also, you can run with a specific GUI style from the command line with, e.g

`zesarux --gui-style zesarux`

Other GUI styles are,

`ZEsarUX ZXSpectr ZX80/81 Z88 CPC MSX Sam ManSoftware QL RetroMac Borland Solarized Dark Solarized Light Clean CleanInverse`

One of those GUI styles might launch correctly for you.

When you run without a custom config file Zesarux just recreates a default one.

If you didn't install the Essential Software using the installer script you can install the extra packages manually using,

`sudo apt install build-essential gcc g++ libqtwebkit-dev libsdl2* sdllib libqt5* qt5* libssl libsndfile schedtool libpthread* sox gzip curl git`

That will install QT5. I can't recall whether 20.04 has QT4 or QT5 installed by default. If QT5 causes issues you can revert back to QT4.
